[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "databricks-storage-utils"
version = "0.1.0"
requires-python = ">=3.9"

[tool.hatch.build.targets.wheel]
packages = ["src/databricks_storage_utils"]